from dataclasses import replace
import json
from pathlib import Path

import pytest

from spectratrack.detection_replay import DetectionReplay, ReplayFrame, ReplayMetadata
from spectratrack.tracking_smoke import (
    TRACKING_SMOKE_MANIFEST_SCHEMA,
    build_tracking_smoke_manifest,
    result_sha256,
    tracking_smoke_gate,
    validate_tracking_smoke_manifest,
)


def _replay(frame_count: int = 600) -> DetectionReplay:
    metadata = ReplayMetadata(
        source_commit="source",
        video="golden/public/mot17/MOT17-04",
        video_sha256="video-sha",
        detector="detector",
        model_sha256="model-sha",
        provider="CPUExecutionProvider",
        config={},
        width=1920,
        height=1080,
    )
    frames = tuple(
        ReplayFrame(
            video=metadata.video,
            frame=index,
            timestamp_s=index / 30.0,
            width=metadata.width,
            height=metadata.height,
            detections=(),
        )
        for index in range(frame_count)
    )
    return DetectionReplay(
        metadata=metadata,
        frames=frames,
        source_sha256="replay-file-sha",
    )


def _metrics(**updates):
    base = {
        "tracking_recall": 0.90,
        "id_switches": 100,
        "fragmentations": 20,
        "false_track_creations": 10,
        "recovery_events": 5,
        "mean_recovery_latency_frames": 2.0,
        "recovered_same_id": 4,
        "wrong_recovery": 1,
        "mean_uninterrupted_track_length": 10.0,
        "uninterrupted_segments": 20,
        "matched_gt": 900,
        "gt": 1000,
    }
    base.update(updates)
    return base


def test_smoke_manifest_uses_two_contiguous_windows_for_600_frame_replay():
    replay = _replay()
    manifest = build_tracking_smoke_manifest(replay, "gt-sha")
    assert manifest["schema"] == TRACKING_SMOKE_MANIFEST_SCHEMA
    assert manifest["selected_frame_count"] == 400
    assert [window["start_position"] for window in manifest["windows"]] == [0, 400]
    assert manifest["windows"][0]["frame_ids"] == list(range(200))
    assert manifest["windows"][1]["frame_ids"] == list(range(400, 600))
    assert manifest["selection"]["candidate_outcome_independent"] is True
    assert manifest["selection"]["tracker_reset_between_windows"] is True


def test_smoke_manifest_validation_fails_closed_on_replay_or_window_change():
    replay = _replay()
    manifest = build_tracking_smoke_manifest(replay, "gt-sha")
    validate_tracking_smoke_manifest(
        replay, manifest, ground_truth_hash="gt-sha"
    )
    changed = replace(replay, source_sha256="other")
    with pytest.raises(ValueError, match="source_replay_file_sha256"):
        validate_tracking_smoke_manifest(
            changed, manifest, ground_truth_hash="gt-sha"
        )
    mutated = json.loads(json.dumps(manifest))
    mutated["windows"][0]["frame_ids"][3] = 999
    with pytest.raises(ValueError, match="frame_ids"):
        validate_tracking_smoke_manifest(
            replay, mutated, ground_truth_hash="gt-sha"
        )


def test_smoke_gate_rejects_obvious_id_switch_regression():
    verdict = tracking_smoke_gate(_metrics(), _metrics(id_switches=101))
    assert verdict["classification"] == "reject_obvious_harm"
    assert verdict["decision"] == "REJECT BEFORE FULL CANONICAL REPLAY"
    assert verdict["gates"]["no_id_switch_regression"] is False


def test_smoke_gate_does_not_require_full_promotion_power():
    verdict = tracking_smoke_gate(_metrics(), _metrics(id_switches=95))
    assert verdict["classification"] == "survivor_or_ambiguous"
    assert verdict["decision"] == "PROCEED TO FULL CANONICAL REPLAY"
    assert verdict["full_promotion_gate_signal_only"]["passed"] is False


def test_result_hash_is_order_independent_and_stable():
    left = {"schema": "x", "nested": {"b": 2, "a": 1}}
    right = {"nested": {"a": 1, "b": 2}, "schema": "x"}
    assert result_sha256(left) == result_sha256(right)


def test_checked_in_smoke_manifest_is_exactly_400_frames_when_present():
    path = (
        Path(__file__).resolve().parents[1]
        / "benchmarks"
        / "vnext"
        / "tracking"
        / "mot17-04-smoke400-v1.json"
    )
    if not path.exists():
        pytest.skip(
            "frozen smoke manifest is generated by the triage workflow"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    assert manifest["schema"] == TRACKING_SMOKE_MANIFEST_SCHEMA
    assert manifest["selected_frame_count"] == 400
    assert [len(window["frame_ids"]) for window in manifest["windows"]] == [200, 200]
